\i Views/schemata.sql
\i Views/base_table.sql
\i Views/deletable_table.sql
\i Views/insertable_table.sql
\i Views/unique_key_constraint.sql
\i Views/foreign_key_constraint.sql
\i Views/table_dependency.sql
\i Views/unreferenced_table.sql
\i Views/table_graph_path.sql
\i Views/table_delete_order.sql
\i Views/table_insert_order.sql